# Travis-CI script for Java/Maven projects
#
# Copyright: Richard Kavanagh.
#
# This code is licensed under an Apache 2.0 license. Please, refer to the LICENSE.TXT file for more information

language: java

jdk:
  - oraclejdk8
  - oraclejdk7